#!/usr/bin/env bash
# This script uses while loop to tell a story about each user in /etc/passwd dir
while IFS=: read -r username password user_id group_id info home shell
do
    echo "The user $username is part of the $group_id gang, lives in $home and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
