#!/usr/bin/env bash
# This while loops keeps printing best school until the condition becomes false once it bomes false / more than 10 it stops
i="0"
while [ $i -lt 10 ]; do
    echo "Best School"
    i=$((i + 1))
done
