#!/usr/bin/env bash
#this script uses while loop to print best  school 10 times but after the 9 print it uses conditional if to print a hi
i="0"
while [ $i -lt 10 ]; do

    if [ $i == 9 ]; then
      echo "Hi"
    fi

    echo "Best School"
    i=$((i + 1))
done
