#!/usr/bin/env bash
#this script uses while loop to print best  school every other time apart for 4th & 8th iteration 
i="0"
while [ $i -lt 10 ]; do

    if [ $i == 3 ]; then
      echo "bad luck"
    elif [ $i == 7 ]; then
      echo "good luck"
    else
      echo "Best School"
    fi

    i=$((i + 1))
done
