#!/usr/bin/env bash
#this script uses the while loop to print numbers and messages where case is initiated
i=1
while [ $i -lt 20 ]; do

    case $i in
        5)
            echo "bad luck from China"
            ;;
        10)
            echo "bad luck from Japan"
            ;;
        18)
            echo "bad luck from Italy"
            ;;
    esac
    echo "$i"
    i=$((i + 1))
done
