#!/usr/bin/env bash
# conditional statemets to check school file
if [ -f "school" ]; then
   echo "school file exists"
   echo "school is a regular file"

   if [ ! -s "school" ]; then
      echo "school file is empty"
   else
     echo "school file is not empty"
   fi

   if [ ! -s "school" ]; then
      echo "school file is empty"
   else
     echo "school file is not empty"
   fi

else
   echo "school file does not exist"
fi

