#!/usr/bin/env bash
# this scripyt starts stops or restarts manage_my_process

case "$1" in
    start)
        "./manage_my_process" &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
        fi
        echo "manage_my_process stopped"
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
        fi
        "./manage_my_process" &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
